Models/ErrorViewModel.cs
using System;

namespace PersonalSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalSite.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PersonalSite.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult thankyou()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using PersonalSite.Models;

namespace PersonalSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Projects()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PersonalSite.Controllers
{
    public class ProjectController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/About/Index.cshtml
<div class="container pt-2 text-white" style="padding-bottom:100px">
    <div class="row">
        <div class="col-12">
            <h1 class="h2 text-warning text-center p-2">About me</h1>
        </div>
        <div>
            <div class="row">
                <div class="col-xs-12 col-md-6">
                    <h3>Who is Trevor?</h3>
                    <p>
                        Hi, my name is Trevor and I like solving problems. In my free time you can usually catch me coding, playing video games, watching a movie, or playing with my dog. Sometimes all at the same time.
                    </p>
                    <h3>How did I start programming?</h3>
                    <p>
                        I told one of my programmer friends that I started learning SQL. He asked me what language I was planning to use that in, and recommended I start learning C#. Then he kept asking if I could do this thing or that thing and I was hooked on solving whatever problem was presented. Before I knew it I started looking for my own problems that I could try and figure out how to solve, and I just never stopped.
                    </p>

                    <h3>What's next?</h3>
                    <p>
                        I'm looking to learn as much as I can about programming, from design patterns and algorithms, to how to best setup a workstation and do basic cable management. Everyday I want to know a little more than the day before.
                    </p>
                </div>
                <div class="col-xs-12 col-md-6 align-self-center text-center">
                    <img src="/photos/me-linkedin.jpg" class="img-fluid rounded-circle h-auto" alt="Me" style="max-width:50%">
                </div>
            </div>
        </div>
    </div>
</div>

Views/Contact/Index.cshtml
<div class="parallax background-mountain">
    <div class="container-fluid paralax-font min-vh-100" style="padding-bottom:10px">
        <form action="https://formsubmit.co/2a04ecb07aab90a27da215270fb73022" method="post" class="needs-validation">
            <input type="hidden" name="_next" value="https://trevorreeves.azurewebsites.net/contact/thankyou">
            <input type="hidden" name="_subject" value="New submission!">
            <div class="container text-white align-self-center justify-content-center pb-2">
                <!--First / Last name etc -->
                <h1 class="col-12 text-center text-warning">Contact Me</h1>
                <div class="row justify-content-center">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="form-label" for="firstName">First Name:</label>
                            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name" required>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="form-label" for="lastName">Last Name:</label>
                            <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Enter Last Name" required>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="form-group">
                            <label class="form-label" for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email" required>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="form-group">
                            <label class="form-message" for="message">Message</label>
                            <textarea type="textarea" class="form-control" id="message" name="message" placeholder="Your Message" rows="6"></textarea>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <button type="submit" class="btn btn-primary btn-lg" id="submit">Submit</button>
                        <button type="reset" class="btn btn-primary btn-lg">Reset</button>
                    </div>
                </div>
            </div> <!--End of Container-->
        </form>
    </div>
</div>

Views/Contact/thankyou.cshtml
<div container>
    <div class="row">
        <div class="col-12 text-center text-white">
            <h1>Thank you! Your message was successfully sent</h1>
            <a href="https://trevorreeves.azurewebsites.net">Return to Homepage</a>
        </div>
    </div>
</div>

Views/Home/About.cshtml
<div class="container pt-2 remaining-height text-white">
    <div class="row">
        <div class="col-12">
            <h1 class="h2 text-warning text-center p-2">About me</h1>
        </div>
        <div>
            <div class="row">
                <div class="col-xs-12 col-md-6">
                    <h3>Who is Trevor?</h3>
                    <p>
                        Hi, my name is Trevor and I like solving problems. In my free time you can usually catch me coding, playing video games, watching a movie, or playing with my dog. Sometimes all at the same time.
                    </p>
                    <h3>How did I start programming?</h3>
                    <p>
                        I told one of my programmer friends that I started learning SQL. He asked me what language I was planning to use that in, and recommended I start learning C#. Then he kept asking if I could do this thing or that thing and I was hooked on solving whatever problem was presented. Before I knew it I started looking for my own problems that I could try and figure out how to solve, and I just never stopped.
                    </p>

                    <h3>What's next?</h3>
                    <p>
                        I'm looking to learn as much as I can about programming, from design patterns and algorithms, to how to best setup a workstation and do basic cable management. Everyday I want to know a little more than the day before.
                    </p>
                </div>
                <div class="col-xs-12 col-md-6 align-self-center text-center">
                    <img src="/photos/me-linkedin.jpg" class="img-fluid rounded-circle h-auto" alt="Me" style="max-width:50%">
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
<div class="parallax background-mountain">
    <div class="container-fluid remaining-height paralax-font">
        <div class="row" style="height: 75%;">
            <div class="col-md-8">
            </div>
            <div class="col-md-4 text-center text-md-left align-self-center">
                <h1>Hi,</h1>
                <p class="lead"> I'm Trevor,</p>
                <p class="lead text-warning">Full Stack Developer.</p>
                <p class="lead">Passionate about all things .NET </p>
            </div>
        </div>
    </div>
    <div class="container-fluid paralax-fontdarker">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="text-warning text-center">My Skills</h2>
                </div>
            </div>
            <div class="text-light p-5">
                <div class="d-flex flex-wrap justify-content-between">
                    <div>
                        <h3 class=" text-center">Languages</h3>
                        <ul>
                            <li>HTML</li>
                            <li>CSS</li>
                            <li>JavaScript</li>
                            <li>C#</li>
                        </ul>
                    </div>
                    <div>
                        <h3 class="text-center">Tools</h3>
                        <ul>
                            <li>Visual Studio</li>
                            <li>Visual Studio Code</li>
                            <li>GitHub</li>
                            <li>Fork</li>
                        </ul>
                    </div>
                    <div>
                        <h3 class="text-center">Frameworks</h3>
                        <ul>
                            <li>ASP.NET Core</li>
                            <li>Entity Framework</li>
                            <li>Bootstrap</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    
    </div>
</div>

Views/Home/testingground.cshtml
<div class="parallax background-mountain">
    <div class="container-fluid remaining-height">
        <div class="row" style="height: 100%;">
            <div class="col-sm-2 h-auto">
                <div class="row paralax-font" style="height:100%">
                    <div class="col-sm-12 align-self-center">
                        <p class="text-center">Text Center Left</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-10 h-auto paralax-font">
                <div class="row">
                    <div class="col-12" style="padding-top: 15px">
                        <p>SOME OTHER TEXT</p>
                    </div>
                    <div class="col-12">
                        <p>SOME OTHER TEXT</p>
                    </div>
                    <div class="col-12">
                        <p>SOME OTHER TEXT</p>
                    </div>
                    <div class="col-12">
                        <p>SOME OTHER TEXT</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Project/Index.cshtml
<div class="container p-3" >
    <div class="d-flex flex-wrap align-items-start justify-content-around" style="row-gap:2em; padding-bottom: 50px">

        <div class="card" style="width: 24rem;">
            <img class="card-img-top" src="~/photos/portfolio_homepage.png" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title lead"><b>Portfolio Website - Static Website</b></h5>
                <p class="card-text"> <div class="lead">Description:</div> A website using ASP.NET Core MVC hosted on Azure to practice Front-End and showcase projects I've created.</p>
            </div>
            <div class="text-center">
                <button class="btn btn-primary w-75" data-toggle="collapse" data-target="#card1">Show More</button>
            </div>
            <ul class="list-group list-group-flush collapse" id="card1">
                <li class="list-group-item">
                    <b>Challenges:</b> The biggest challenge was vertical alignment, with responsive design in mind. Two areas I had trouble aligning vertically were
                    making sure that the fixed navbar wasn't covering text in the body, and keeping the footer stuck to the bottom.
                </li>
                <li class="list-group-item">
                    <b>Solutions:</b> Adding padding to the body top helps prevent the fixed navbar from covering text. The footer was floating up was really an issue of text breaking out of a container
                    with a calulated height. This was fixed by adding a min-height to the container so the text doesn't break out.
                </li>
                <li class="list-group-item">
                    <b>What I learned:</b> I learned that designing a simple website from scratch can be difficult,
                    not in terms of code complexity but in terms of choosing colors, designing layouts, figuring out what look you want to acheive, etc.
                    With Bootstrap I learned: using the grid system, flexbox, aligning text, navbars, and more. I also learned that you can use calc() in css to calculate height.
                </li>
            </ul>
            <div class="card-body">
                <a href="https://trevorreeves.azurewebsites.net/" class="card-link" target="_blank" rel="noopener noreferrer">Project</a>
                <a href="https://github.com/reevest2/personalwebsite" class="card-link" target="_blank" rel="noopener noreferrer">Github</a>
            </div>
        </div>


        <div class="card" style="width: 24rem;">
            <img class="card-img-top" src="~/photos/movies_homepage.png" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title lead"><b>Movies Website - Fullstack Web App</b></h5>
                <p class="card-text"> <div class="lead">Description:</div>A website sitting on top of an API to connect to MongoDB with full CRUD operations.</p> <br>
            </div>
            <div class="text-center">
                <button class="btn btn-primary w-75" data-toggle="collapse" data-target="#card2">Show More</button>
            </div>
            <ul class="list-group list-group-flush collapse" id="card2">
                <li class="list-group-item">
                    <b>Challenges:</b> This project was full of challenges. From trying to learn about depenency injection, generics, to trying to connect to the API.
                </li>
                <li class="list-group-item">
                    <b>Solutions:</b> Just get started and try and figure out as much as I could on my own. Usually I could get about 95% of the way there, and ask for help on the last bit to get it working.
                </li>
                <li class="list-group-item">
                    <b>What I learned:</b> I learned about dependency injection and what the pattern looks like. I also learned about using generics.
                </li>
            </ul>
            <div class="card-body">
                <a href="https://movies20210929194249.azurewebsites.net/" class="card-link" target="_blank" rel="noopener noreferrer">Project</a>
                <a href="https://github.com/reevest2/movies" class="card-link" target="_blank" rel="noopener noreferrer">Github</a>
            </div>
        </div>


        <div class="card" style="width: 24rem;">
            <img class="card-img-top" src="~/photos/api_homepage.png" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title lead"><b>Movies API - API</b></h5>
                <p class="card-text"> <div class="lead">Description:</div>An API used to connect to MongoDB repository.</p> <br>
            </div>
            <div class="text-center">
                <button class="btn btn-primary w-75" data-toggle="collapse" data-target="#card3">Show More</button>
            </div>
            <ul class="list-group list-group-flush collapse" id="card3">
                <li class="list-group-item">
                    <b>Challenges:</b> This project was full of challenges. From trying to learn about llambda expression, generics, to setting up the connection string.
                </li>
                <li class="list-group-item">
                    <b>Solutions:</b> Just get started and try and figure out as much as I could on my own. Usually I could get about 95% of the way there, and ask for help on the last bit to get it working.
                </li>
                <li class="list-group-item">
                    <b>What I learned:</b> After this project I was more comfortable using properties, generics, llambda expressions, and identifying the dependency injection pattern.
                </li>
            </ul>
            <div class="card-body">
                <a href="https://movieapi20210928214652.azurewebsites.net/index.html" class="card-link" target="_blank" rel="noopener noreferrer">Project</a>
                <a href="https://github.com/reevest2/movies-api" class="card-link" target="_blank" rel="noopener noreferrer">Github</a>
            </div>
        </div>


        <div class="card" style="width: 24rem;">
            <img class="card-img-top" src="~/photos/stopwatch.png" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title lead"><b>Stopwatch - C# Console App</b></h5>
                <p class="card-text"> <div class="lead">Description:</div>A simple C# console app to create a stopwatch.</p> <br>
            </div>
            <div class="text-center">
                <button class="btn btn-primary w-75" data-toggle="collapse" data-target="#card4">Show More</button>
            </div>
            <ul class="list-group list-group-flush collapse" id="card4">
                <li class="list-group-item">
                    <b>Challenges:</b> This project was relatively straightforward, the biggest challenge was trying to make as many classes private as possible.
                </li>
                <li class="list-group-item">
                    <b>Solutions:</b> Create a minimal viable product quickly, and refactor to conform to best practices.
                </li>
                <li class="list-group-item">
                    <b>What I learned:</b> I learned that private classes should begin with an underscore "_". I also learned that you should make your methods public, but keep properties private so they cannot be manipulated by outside classes.
                </li>
            </ul>
            <div class="card-body">
                <a href="https://github.com/reevest2/stopwatch" class="card-link" target="_blank" rel="noopener noreferrer">Github</a>
            </div>
        </div>

        <div class="card" style="width: 24rem;">
            <img class="card-img-top" src="~/photos/comic.png" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title lead"><b>Xkcd Comic - Discord Bot</b></h5>
                <p class="card-text"> <div class="lead">Description:</div>A Discord bot that uses the XKCD Api to return a comic</p> <br>
            </div>
            <div class="text-center">
                <button class="btn btn-primary w-75" data-toggle="collapse" data-target="#card5">Show More</button>
            </div>
            <ul class="list-group list-group-flush collapse" id="card5">
                <li class="list-group-item">
                    <b>Challenges:</b> Getting the program.cs file setup was the toughest part of this. Once that was setup adding new commands is pretty straightforward.
                </li>
                <li class="list-group-item">
                    <b>Solutions:</b> Utilize video resources to get the progam.cs file setup. From there I could use the knowledge I have to create models and consume the Xkcd api.
                </li>
                <li class="list-group-item">
                    <b>What I learned:</b> I learned how to use the package manager to get packages from other than Nuget. I also learned that you can use the console app to make more than just writing lines to the console, or that the discord app is like writing lines on a console.
                </li>
            </ul>
            <div class="card-body">
                <a href="https://github.com/reevest2/xkcdbot" class="card-link" target="_blank" rel="noopener noreferrer">Github</a>
            </div>
        </div>


    </div>
</div>

Views/Shared/_Footer.cshtml
<div class="container">
    <div class="row justify-content-between">
        <div class="col-auto">
            &copy; @DateTime.Now.Year - Trevor Reeves | <a href="~/photos/Trevor_Reeves_Resume.pdf" target="_blank" rel="noopener noreferrer">View Resume</a>
        </div>
        <div class="col-auto pl-sm-2">
            <a class="px-1" href="https://www.linkedin.com/in/trevorreeves/"  target="_blank" rel="noopener noreferrer"><i class="fab fa-linkedin"></i></a>
            <a class="px-1" href="https://github.com/reevest2"  target="_blank" rel="noopener noreferrer"><i class="fab fa-github"></i></a>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trevor Reeves</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/parallax.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: rgb(18 18 18);">
    <header>
        @await Html.PartialAsync("_NavBar") 
    </header>

    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-dark text-white">
        @await Html.PartialAsync("_Footer")
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand d-flex w-25 mr-auto justify-content-start"
           asp-area="" asp-controller="Home" asp-action="Index"><img src="~/navbar-icon.png" /><span class="align-self-center d-none d-sm-block">eeves</span></a>
        <div class="navbar-nav w-50 justify-content-center">
            <div class="nav-item">
                <button type="submit" class="btn btn-primary" onclick="window.open('/photos/Trevor_Reeves_Resume.pdf')">View Resume</button>
            </div>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav ml-auto w-100 justify-content-end p-sm-1">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="About" asp-action="Index">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                </li>
            </ul>
        </div>
    </div>
</nav> 